### ISSUE TITLE
Layerzero v2 audit `H1` and `L1` explanation (details) is exactly same  

### ISSUE THREAD

**Issue by AbhishekThak344** [windhustler/audits#1]
https://github.com/windhustler/audits/blob/master/solo/LayerZero-V2-Security-Review.pdf

H1 and L1 finding share same details. Is it intentional or misconfiguration while generating pdf report.

**Comment by windhustler** [comment]
Huh, thanks for letting me know! It's a mistake, I'll fix it!

**Comment by AbhishekThak344** [comment]
Thank you. Your audit reports / contents provide lot of value. :)
